version: '3'

services:

  mysql-db:
    build: .
    volumes:
      - db-volume:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: paintFactoryDb123
      MYSQL_DATABASE: paintFactoryDb
    ports:
      - "3306:3306"