version: '3.7'

services:
  mysql-db:
    build: .
    volumes:
      - db-data:/var/lib/db/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "paintFactoryDb123"
      MYSQL_DATABASE: "paintFactoryDb"
    ports:
      - "3306:3306"
    expose:
      - "3306"

volumes:
  db-data: